spring:
  profiles:
    active: ${PROFILE}
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${MARIADB_HOST}:${MARIADB_PORT}/${DATASOURCE_DATABASE_NAME}?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    open-in-view: false

admin-password: ${ADMIN_PASSWORD}
algorithm-manager-password: ${ALGORITHM_MANAGER_PASSWORD}