### 코드 상세 조회
GET http://localhost:8080/api/v1/codes/5

### 코드 작성
POST http://localhost:8080/api/v1/codes?problem=4
Content-Type: application/json

{
  "solver": "김문기",
  "content": "codecode!",
  "password": "비밀번호"
}

### 코드 수정
PATCH http://localhost:8080/api/v1/codes/5
Content-Type: application/json

{
  "solver": "김문기",
  "content": "code!",
  "password": "비밀번호"
}

### 코드 삭제
DELETE http://localhost:8080/api/v1/codes/5
Content-Type: application/json

{
  "solver": "김문기",
  "password": "비밀번호"
}

### 문제별 코드 타입 변경
POST http://localhost:8080/api/v1/codes/type
Content-Type: application/json

{
  "problem": 4,
  "code": 5,
  "type": "best",
  "password": "aP7mS3zX#2L8oQ9wE4y&"
}