### 문제별 코드 목록 조회
GET http://localhost:8080/api/v1/code?problem=3

### 코드 상세 조회
GET http://localhost:8080/api/v1/code/4

### 문제의 베스트 코드 조회
GET http://localhost:8080/api/v1/code/best?problem=1

### 문제의 참신한 코드 조회
GET http://localhost:8080/api/v1/code/novel?problem=1

### 코드 작성
POST http://localhost:8080/api/v1/code?problem=3
Content-Type: application/json

{
  "solver": "김문기",
  "code": "codecode",
  "password": "비밀번호"
}

### 코드 수정
PATCH http://localhost:8080/api/v1/code/6
Content-Type: application/json

{
  "solver": "김문기",
  "code": "!!!",
  "password": "비밀번호"
}

### 코드 삭제
DELETE http://localhost:8080/api/v1/code/5
Content-Type: application/json

{
  "solver": "김문기",
  "password": "비밀번호"
}

### 문제별 코드 타입 변경
POST http://localhost:8080/api/v1/code/type
Content-Type: application/json

{
  "problem": 1,
  "solver": "조재혁",
  "type": "novel",
  "password": "1234"
}