### 문제 리스트 조회
GET http://localhost:8080/api/v1/problems

### 문제별 코드 목록 조회
GET http://localhost:8080/api/v1/problems/3/codes

### 문제의 타입별 코드 조회
GET http://localhost:8080/api/v1/problems/1/best

### 문제 추가
POST http://localhost:8080/api/v1/problems
Content-Type: application/json

{
  "name": "문제333",
  "date": "20240208",
  "password": "qRp2#L9zF!oP5xY7sE8a"
}